[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
hashbrown = "0.13.2"
nom = "7.1.3"
once_cell = "1.17.1"

